version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: superset_db
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - superset_net

  superset:
    image: apache/superset
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key
      - ADMIN_USERNAME=admin
      - ADMIN_FIRST_NAME=Superset
      - ADMIN_LAST_NAME=Admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
      - DATABASE_URL=mysql://superset:superset123@mysql:3306/superset_db
      - KEYCLOAK_CLIENT_ID=superset-client
      - KEYCLOAK_CLIENT_SECRET=client-secret
      - KEYCLOAK_BASE_URL=http://keycloak:8080
      - KEYCLOAK_REALM=superset-realm
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
    ports:
      - "8088:8088"
    depends_on:
      - mysql
    networks:
      - superset_net
    command: >
      /bin/bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "

volumes:
  mysql_data:

networks:
  superset_net:
    external: true

