# File: .github/workflows/action.yml

name: Test Node App

on:
  push:
    branches: [main, dev, uat]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run app (for testing only - GitHub Actions won't expose the port)
      run: node app.js
